services:
  db:
    image: postgres:17-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
#  mazy-product:
#    depends_on:
#      - db
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8081:8081"
#    environment:
#      - SPRING_PROFILES_ACTIVE=postgresql
