apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
type: Opaque
data:
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | b64enc }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | b64enc }}
