replicaCount: 2

image:
  repository: localhost:5001/mazy-product
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8081
  targetPort: 8081

hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

springBoot:
  activeProfile: postgresql

database:
  url: jdbc:postgresql://host.minikube.internal:5432/mazyProduct
  username: mazyProduct
  password: mazyProduct
  driverClassName: org.postgresql.Driver

jpa:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  ddlAuto: update
  showSql: true

custom:
  persistence: postgresql
  paymentGateway: mock
